apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-scheduler
  labels:
    app: ns-scheduler
spec:
  replicas: 1

  selector:
    matchLabels:
      app: ns-scheduler
  template:
    metadata:
      labels:
        app: ns-scheduler
    spec:
      serviceAccountName: ns-scheduler
      terminationGracePeriodSeconds: 60
      containers:
      - name: ns-scheduler
        image: ns-scheduler:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NS_SCHEDULER_UPTIME_SCHEDULE
          value: "1-7 10:00-13:00"
        - name: NS_SCHEDULER_CHECK_INTERVAL
          value: "60"
